name: commitlint for PR title
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
jobs:
  commitlint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - run: git config --global url."https://".insteadOf git://
      - run: npm ci --ignore-scripts
      - name: Apply commitlint to the PR title
        run: echo "${{ github.event.pull_request.title }}" | npx --no-install commitlint
